/**
 * LLM Service Interface
 *
 * Defines the contract for Large Language Model services.
 */

export interface RecommendedPlace {
  name: string
  name_en?: string
  address?: string
  category: string
  description?: string
  latitude?: number
  longitude?: number
}

/**
 * Tool call information from Function Calling
 */
export interface ToolCallChunk {
  id: string
  name: string
  args: Record<string, unknown>
  status: 'pending' | 'executing' | 'completed' | 'failed'
  result?: unknown
}

/**
 * Itinerary preview data generated by AI
 */
export interface ItineraryPreviewData {
  title: string
  days: Array<{
    dayNumber: number
    date: string
    items: Array<{
      order: number
      placeName: string
      placeNameEn?: string
      category: string
      startTime?: string
      duration?: string
      note?: string
      matched?: boolean
    }>
  }>
}

export interface StreamChunk {
  type: 'text' | 'place' | 'tool_call' | 'tool_result' | 'itinerary_preview' | 'done' | 'error'
  content?: string
  place?: RecommendedPlace
  toolCall?: ToolCallChunk
  itineraryPreview?: ItineraryPreviewData
  messageId?: string
}

export interface ChatContext {
  projectId: string
  destination: string
  country?: string
  existingPlaces: Array<{
    id?: string
    name: string
    category: string
    latitude?: number
    longitude?: number
  }>
  conversationHistory: Array<{
    role: 'user' | 'assistant'
    content: string
  }>
  conversationSummary?: string
  itinerary?: {
    id: string
    startDate: string
    endDate: string
    days: Array<{
      dayNumber: number
      date: string
      items: Array<{ placeName: string; startTime?: string }>
    }>
  }
  userPreferences?: {
    topCategories: string[]
    averageRating?: number
  }
}

export interface ILLMService {
  /**
   * Generate a streaming response for a chat message
   * Returns an async iterator of stream chunks
   */
  streamChat(
    message: string,
    context: ChatContext
  ): AsyncGenerator<StreamChunk, void, unknown>

  /**
   * Check if the service is available
   */
  isAvailable(): Promise<boolean>
}

/**
 * Type guard for StreamChunk
 */
export function isTextChunk(chunk: StreamChunk): chunk is StreamChunk & { type: 'text'; content: string } {
  return chunk.type === 'text' && typeof chunk.content === 'string'
}

export function isPlaceChunk(chunk: StreamChunk): chunk is StreamChunk & { type: 'place'; place: RecommendedPlace } {
  return chunk.type === 'place' && chunk.place !== undefined
}

export function isToolCallChunk(chunk: StreamChunk): chunk is StreamChunk & { type: 'tool_call'; toolCall: ToolCallChunk } {
  return chunk.type === 'tool_call' && chunk.toolCall !== undefined
}

export function isItineraryPreviewChunk(chunk: StreamChunk): chunk is StreamChunk & { type: 'itinerary_preview'; itineraryPreview: ItineraryPreviewData } {
  return chunk.type === 'itinerary_preview' && chunk.itineraryPreview !== undefined
}

export function isDoneChunk(chunk: StreamChunk): chunk is StreamChunk & { type: 'done' } {
  return chunk.type === 'done'
}

export function isErrorChunk(chunk: StreamChunk): chunk is StreamChunk & { type: 'error' } {
  return chunk.type === 'error'
}
